### ISSUE TITLE
Methods: telomerase activity prediction 

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-manuscript#76]
@NNoureen and @syzheng used their method EXTEND to quantify telomerase activity and performed a number of comparisons [`AlexsLemonade/OpenPBTA-analysis/analyses/telomerase-activity-prediction`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/telomerase-activity-prediction). This issue is to track the addition of a telomerase activity prediction section to the methods section of the manuscript.

**Comment by NNoureen** [comment]
Thanks. 
We have a problem. While building the build.sh we are getting some errors due to some analysis file links.  Following is the error log. Kindly help us to resolve this issue.

(manubot) noureen@cbbi16:~/OpenPBTA-manuscript$ sh build/build.sh
Retrieving and processing reference metadata
## INFO
Manuscript content parts:
00.front-matter
01.abstract
02.introduction
03.methods
04.results
05.conclusions
90.back-matter
## INFO
65 unique citations strings extracted from text
65 unique standard citations
## INFO
requests-cache starting with 0 cached responses
## WARNING
Error parsing web_query output as JSON for https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/immune-deconv/plots/corrplot_xCell_vs_CIBERSORT:
Remote page not found
## WARNING
Error in get_url_citeproc_zotero for https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/immune-deconv/plots/corrplot_xCell_vs_CIBERSORT due to a JSONDecodeError:
Expecting value: line 1 column 1 (char 0)
## INFO
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/UTHSCSA/noureen/miniconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/url.py", line 17, in get_url_citeproc
    return retriever(url)
  File "/home/UTHSCSA/noureen/miniconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/url.py", line 35, in get_url_citeproc_zotero
    zotero_data = web_query(url)
  File "/home/UTHSCSA/noureen/miniconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/zotero.py", line 38, in web_query
    raise error
  File "/home/UTHSCSA/noureen/miniconda3/envs/manubot/lib/python3.6/site-packages/manubot/cite/zotero.py", line 35, in web_query
    zotero_data = response.json()
  File "/home/UTHSCSA/noureen/miniconda3/envs/manubot/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/UTHSCSA/noureen/miniconda3/envs/manubot/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/UTHSCSA/noureen/miniconda3/envs/manubot/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/UTHSCSA/noureen/miniconda3/envs/manubot/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
## WARNING

**Comment by jaclyn-taroni** [comment]
Tagging @cgreene as he has more Manubot experience. I have not built the manuscript locally myself.

**Comment by jashapiro** [comment]
Hi @NNoureen! Do you need to build locally for your updates? It may be fine to only update the `content/03.methods.md` file at this point with your methods, push those changes, and then let the automatic build on github take care of the rest.

**Comment by NNoureen** [comment]
Sure we will update the content/03.methods.md and will submit that. Thanks for the help.

**Comment by jaclyn-taroni** [comment]
Closed via #100
